services:
  web:
    build: .
    image: rancang-belanja:latest
    container_name: rancang-belanja
    ports:
      - "8088:3000"
    volumes:
      - rancang_data:/data
    restart: unless-stopped

volumes:
  rancang_data:
